cpm = int(input("Input chirps per minute as an integer: "))
fahrenheit = 50 + ((cpm -40)/4)
celsius = 10 + ((cpm -40)/7)
print("temperature (Fahrenheit):",fahrenheit)
print("temperature (Celsius):",celsius)